default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRESS_EMAIL'] %>
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: MicroProfile_development

test:
  <<: *default
  database: MicroProfile_test

